spring.application.name=HRProject

server.port=9090

# Optional - JPA settings

spring.jpa.hibernate.ddl-auto=validate
server.address=172.29.192.1


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=HR_Project;encrypt=true;trustServerCertificate=true
## spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=eShop;encrypt=false

# USE eShop;
# CREATE USER MyUser FOR LOGIN MyUser;
# ALTER ROLE db_owner ADD MEMBER MyUser;



spring.datasource.username=MyUser
spring.datasource.password=1022000
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
